# This is a basic workflow to help you get started with Actions

name: OpenHD Image Writer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "qml" branch
  push:
    branches: [ "5.15.7" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/setup.deb.sh' | sudo -E bash
          sudo apt update
          sudo apt upgrade
          sudo apt install -y --no-install-recommends libgnutls28-dev build-essential devscripts debhelper cmake git libarchive-dev libcurl4-openssl-dev libqt5svg5-dev libssl-dev qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-templates2 qml-module-qtquick-window2 qml-module-qtgraphicaleffects  openhd-qt-x86-jammy 
          mkdir build
          mv `ls -A | grep -v "build"` build
          cd build
          debuild -uc -us
          cd ..
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD Image Writer"
          path: |
            *.deb
          if-no-files-found: error

      # - name: Push
      #   id: push
      #   uses: cloudsmith-io/action@master
      #   with:
      #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      #     command: "push"
      #     format: "deb"
      #     owner: "openhd"
      #     repo: "openhd-2-3-evo"
      #     distro: "ubuntu"
      #     release: "jammy"
      #     republish: "true" # needed ONLY if version is not changing
      #     file: "*.deb"