name: OpenHD Image Writer Windows

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "master"

   paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '**.adoc'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
            uses: jurplel/install-qt-action@v3
            with:
              version: ${{ env.QT_VERSION }}
              aqtversion: ==3.1.*
              host: windows
              target: desktop
              arch: win32_mingw81
              modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d
              setup-python: true
              tools: 'tools_cmake'

    - name: Install dependencies
      run: |
        choco install -y nsis openssl.light
        mkdir C:\files
        xcopy "C:\Program Files\OpenSSL" C:\files /E /I /Q
        dir "C:\files"

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles" -DOPENSSL_ROOT_DIR="C:\files" -DCMAKE_TOOLCHAIN_FILE="C:\Qt\${{env.QT_VERSION}}\${{env.QT_VERSION}}\mingw32\isystem.cmake"

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cd ../build/
        dir
        makensis openhdimagewriter.nsi

    - name: Upload to Github  
      uses: 'actions/upload-artifact@v3'
      with:
        name: "OpenHD Image Writer"
        path: |
          *.exe
        if-no-files-found: error
