name: OpenHD Image Writer Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
     
    - name: Install dependencies
      run: |
        #choco install -y openssl.light
        choco install -y nsis

    - name: Configure CMake & Build
      run: |
        #cmake -S src -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build build -- -j2
        
    - name: Sign Installer
      if: success()
      run: |
        # Sign the installer here if you have a proper code signing certificate and signtool.exe installed
