name: OpenHD Image Writer Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'

    - name: Install dependencies
      run: |
        choco install -y nsis openssl.light
        dir "C:/Program Files/OpenSSL/"

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles" -DOPENSSL_ROOT_DIR="C:/Program Files/OpenSSL"

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cd ../build/
        dir
        makensis openhdimagewriter.nsi

    - name: Upload to Github  
      uses: 'actions/upload-artifact@v3'
      with:
        name: "OpenHD Image Writer"
        path: |
          *.exe
        if-no-files-found: error
